package com.assessment.coffeeshop.config;

import java.net.URI;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClient;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension;
import software.amazon.awssdk.enhanced.dynamodb.extensions.VersionedRecordExtension;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.dynamodb.DynamoDbClient;

@Configuration
@Profile({"!local"})
public class DynamoDBConfiguration {

  @Value("${cloud.aws.dynamodb.endpoint}")
  private String endpoint;

  @Value("${cloud.aws.sqs.region}")
  private String region;

  @Bean
  public DynamoDbClient dynamoDbClient() {
    return DynamoDbClient.builder()
        .endpointOverride(URI.create(endpoint))
        .region(Region.of(region))
        .build();
  }

  @Bean
  public DynamoDbEnhancedClient dynamoDbEnhancedClient() {
    var versionedRecordExtension = VersionedRecordExtension.builder().build();
    var autoGeneratedTimestampRecordExtension = AutoGeneratedTimestampRecordExtension.builder().build();
    return DynamoDbEnhancedClient.builder()
        .dynamoDbClient(dynamoDbClient())
        .extensions(versionedRecordExtension, autoGeneratedTimestampRecordExtension)
        .build();
  }

}
