spring:
  jpa:
    properties:
      hibernate:
        show_sql: true

cloud:
  aws:
    region:
      static: us-east-1
    credentials:
      access-key: test
      secret-key: test
    sqs:
      endpoint: http://localhost:4566
