package com.assessment.coffeeshop.infra.repo.entity;

import java.time.Instant;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.SuperBuilder;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbVersionAttribute;

@Setter
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
public class AbstractDynamoEntity {

  protected Integer version;

  @Getter
  @Builder.Default
  protected Instant createdDate = Instant.now();

  protected Instant modifiedDate;

  @DynamoDbVersionAttribute
  public Integer getVersion() {
    return version;
  }

  @DynamoDbAutoGeneratedTimestampAttribute
  public Instant getModifiedDate() {
    return modifiedDate;
  }

}
